
version: 2

sources:
  - name: stripe
    description: Stripe project
    tags:
      - sources
    tables:
      - name: airbyte_subscriptions
        description: Entity
        columns:
          - name: id